### ISSUE TITLE
GitHub support

### ISSUE THREAD

**Issue by undying-fish** [undying-fish/hacker-tracker#1]
-0 be able to output GitHub links from input data @darrenvong @undying-fish

seems like it'd be just a matter of creating a PHP script

```echo '<a href="http://github.com/"' + input + '>' + input + '</a>'```, creates [undying-fish/hacker-tracker](http://github.com/undying-fish/hacker-tracker)~~

**Comment by boardfish** [comment]
- use input from event page to retrieve commit history of repository

e.g. user would input "undying-fish/hacker-tracker" into a form, commit history (short hash, commit message, timestamps) would then be outputted to the database so that they are cleanly visible.

**Comment by boardfish** [comment]
Long-since implemented in ruby port [prep](http://github.com/undying-fish/prep) alpha.
