### ISSUE TITLE
Twitter support

### ISSUE THREAD

**Issue by undying-fish** [undying-fish/hacker-tracker#4]
Allow the user to enter a number of usernames (hackathon account, each team member's account, more if necessary) and query the Twitter database for all tweets between two given datetimes (start and end of hackathon).

The following four fields need to be outputted to the site database:

- username
- datetime
- tweet content
- link

along with an identifier that states that the source of the post is Twitter, so that the right icon is displayed in the summary table.

**Comment by boardfish** [comment]
Long-since implemented in Ruby port [prep](http://github.com/undying-fish/prep).
