### ISSUE TITLE
Port main site to Bootstrap

### ISSUE THREAD

**Issue by undying-fish** [undying-fish/hacker-tracker#5]
- Look into Flat UI and style existing site @szen95 (if opening index.php locally doesn't work, rename it to index.html, but **don't forget to rename it back before you make any commits**

**Comment by undying-fish** [comment]
Basic bootstrap implemented in summary.php, will move across to index.php

**Comment by boardfish** [comment]
After hackathon, summary.php has basic Bootstrap, though main site uses different layout.

**Comment by boardfish** [comment]
Development continuing personally in Ruby at [prep](http://github.com/undying-fish).
